repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Check for latest version on GitHub
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      ## - id: detect-aws-credentials

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0  # Check for latest version
    hooks:
      - id: gitleaks
